# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd38f8e8200e28d0d1b0c6bb3103a4bab14a1686330c3b358ffbce08ffb13aedb5b6f87ef7ea9acf89ebf35d625600a98fef69930f5f680fdfc55f133574a7ad

test:
  secret_key_base: 4ea46a2ebc08814bc691f85412cf2e9f7ea412e004c15fa1c3f0b5a1201de1041ae4d8d921d90f7029c4776944ceaf70ca9d5397c9cdee91ac0eddc0207b4bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
